language: rust
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi
env:
  global:
    - RUST_BACKTRACE: full
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo doc --verbose --all
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    # cargo tarpaulin --out Xml
    # bash <(curl -s https://codecov.io/bash)
  fi
notifications:
  email:
    on_success: never
